### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by nmizukami**
A few minor changes - 
-Makefile (move user define part at top)
-move f90 code in ntop/build to src subdirectory
-create .gitignore file

### CODE REVIEW

**Comment by bartnijssen** [comment]
@martynpclark : Can you review this one?

**Comment by nmizukami** [comment]
@bartnijssen  what is going on for this pull request?

**Comment by bartnijssen** [comment]
@nmizukami : Nothing "going on", but someone needs to review it before it can be merged. It's your job to make sure that happens so find someone to review it.

**Comment by bartnijssen** [comment]
@nmizukami : Still needs code review - please find someone to provide some review.

**Comment by bartnijssen** [comment]
@nmizukami : Looked fine so I went ahead and merged it

**Pull request merged**
